### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Sihaoyu1220** [STAT547-UBC-2019-20/Group10#27]
### Is the repository organized in a useful and sensible way?
The repository is well organized. `data`, `docs`, `scripts`, `images` folder and `README.md` are located in the right place. A few suggestions: move final_report into docs and create another folder to store .rds file.

### Is there a Usage section in the README?
Yes! There is a Usage section and the Usage section is very clear and easy to read. 

### Do the scripts run to completion as described in the README?
Yes! All the scripts run to completion by following the steps in the README!

### Do the scripts produce the expected output?
Yes! The datasets can be successfully downloaded and cleaned; images can be reproduced!

### Are the scripts and functions appropriately documented?
Yes. All the scripts are concise and the comments are clear. Especially in clean_data.R, you checked the path before loading and saving the file, which is great!

### Does it take a long time for the analysis to run? Are there tasks that could be vectorized to make things faster?
No. The analysis runs very fast. In the scripts, there is nothing that needs to use vectorization.

### Are the research questions appropriate and well-chosen?
The research question is really interesting, and it is kind of helpful to prevent the wildfire! A suggestion for your final report, include a data description section to make the meaning of each variable clear. 

### Are the visualizations effectively displayed? How can they be improved? Are there other, more effective visualizations that could or should be used? 
All the labels, titles, legends, and colors are nice! All the plots are informative! A suggestion for your EDA, plot distribution of brightness (boxplot) to see if there are outliers, which may influence your analysis results.

**Comment by luckymeng7** [comment]
Hi sihaoyun,

Thanks for your review, yes, we will better organize our project folder, add a boxplot and include a more detailed description section in the next project release. 

Thanks,
Monica
