### ISSUE TITLE
Milestone 2: Peer Review 

### ISSUE THREAD

**Issue by racquellem** [STAT547-UBC-2019-20/Group10#28]
**(1) Is the repository organized in a useful and sensible way?**

The repository is organized well, with different folders (i.e. `data, docs, images, scripts and tests`) with their corresponding files. It is also easy to identify what these files contain based on their name. 

**(2) Is there a Usage section in the README?**

There is a Usage section in the README which contains simple instructions in how to run their scripts. It also has a very brief explanation of what each script is for. 

**(3) Do the scripts run to completion as described in the README?**

When inputting their scripts to the terminal, they ran very fast and smoothly. The only thing I would comment on is that in addition to the packages they mentioned in the README, I also had to install the `effects` package, but this was no big deal.

**(4) Do the scripts produce the expected output?**

Yes, I was able to see the new clean data, as well as all the plots, in their applicable folders. 

**(5) Are the scripts and functions appropriately documented?**

The scripts were very descriptive in the purpose of each step (especially in `clean_data.R`), simples, and easy to follow!

**(6) Does it take a long time for the analysis to run? Are there tasks that could be vectorized to make things faster?**

It does not take a long time, and there appears to be no tasks that need to be vectorized.

**Additional comments:**
- I couldn't interpret the plots that well or easily, considering the variables this data contains wasn't explained. Hence, would be nice if you add descriptions to your README or even your final report! 
- Overall, the plots are nicely done, but for `effectSizes`, I find it redundant reiterating "plot" in each title. 
- Interesting topic, I actually will be looking at satellite imaging data for my own Masters thesis, where I'll be investigating Asian-derived aerosols (dust, anthropogenic pollutants) in the NE Pacific Ocean and their long range transport to North America! Albeit, these aerosols may have significantly decreased the past few months due to the current pandemic. So, would have definitely been beneficial and really informative for me to understand your dataset more :) 

Cheers,
Racquelle

**Comment by luckymeng7** [comment]
Hi Racquelle,

Thanks for your review, we will definitely add more explanation for explaining the data to the readme file. And thanks for pointing out the missing package, I've added it to the instruction. 

Good luck to your projects and take care.

Thanks,
Monica
