### ISSUE TITLE
Plotting over a map

### ISSUE THREAD

**Issue by stannam** [STAT547-UBC-2019-20/Group10#49]
@yuliaUU Can you help us with how can we plot the fire location over the map of Australia?

Thanks in advance!

**Comment by yuliaUU** [comment]
Here is the code:
library(ggplot2)

ggplot(world, aes(x=long, y=lat)) +
    geom_polygon(aes(group=group)) +
  theme_bw() +
# you just need to replace teh code below with what you need:
  geom_point(data= your_data, aes_string(x=your_data$longitude, y=your_data$latitude)

**Comment by luckymeng7** [comment]
This is awesome! Thanks @yuliaUU and @stannam , I will update it soon

**Comment by luckymeng7** [comment]
Hi @yuliaUU ,

When I try out the method you provide, I got the error saying that 
 > object 'world_map' not found

I've had library(ggplot2) included. is there anything else for me to include?

Also, what do you mean by replace the code for geom_point? Will I still be able to plot the points based on brightness and frp? Could you comment on the following change?

Here is the original code chunk for plotting:
```r
  p <- ggplot() +
   geom_point(data=select_data,aes(x=longitude,y=latitude, size = frp, color=brightness), alpha = 0.5) +
    xlab ("Longitude, degree(East as positive)") +
    ylab ("Latitude, degree(North as positive)") +
    ggtitle('Brightness and Radiation Power vs. Geometric info') +
   theme(plot.title = element_text(hjust = 0.5, size = 14), legend.title = element_text(size=12))
```
And here is how I change it to
```r
  p <- ggplot(world_map,aes(x=longitude,y=latitude, group = group)) +
   # geom_point(data=select_data,aes(x=longitude,y=latitude, size = frp, color=brightness), alpha = 0.5) +
    xlab ("Longitude, degree(East as positive)") +
    ylab ("Latitude, degree(North as positive)") +
    ggtitle('Brightness and Radiation Power vs. Geometric info') +
    geom_polygon(fill="lightgray", colour = "white")+
    theme_bw()
   # theme(plot.title = element_text(hjust = 0.5, size = 14), legend.title = element_text(size=12))
```

**Comment by yuliaUU** [comment]
library(ggplot2)  run it first

**Comment by yuliaUU** [comment]
![image](https://user-images.githubusercontent.com/54612866/78085197-1fc83500-736f-11ea-8b4b-3f03d09d80d5.png)
world <- map_data("world", region="Australia")

ggplot(world, aes(x=long, y=lat)) +
    geom_polygon(aes(group=group)) +
  theme_bw()

**Comment by luckymeng7** [comment]
How can I add the geom_point to it with a different dataframe(my imported data)?

**Comment by yuliaUU** [comment]
ggplot(world, aes(x=long, y=lat)) +
    geom_polygon(aes(group=group)) +
geom_point(aes(x=data$lon, y=data$lat))+
  theme_bw()

**Comment by yuliaUU** [comment]
or try the following:
```
ggplot() +
geom_polygon(world, aes(x=long, y=lat,group=group)) +
geom_point(data, aes(x=lon, y=lat))+
theme_bw()
```

**Comment by luckymeng7** [comment]
Awesome, I've added the polygon on to our plot! Thanks a lot @yuliaUU 

Closing this issue
